"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const ROOT = path.resolve(__dirname, "..");
global.window = global;
for (const filename of ["model.js", "s1sim.js", "s1route.js"]) require(path.join(ROOT, "js", filename));

function verifyMechanics() {
  const state = AD.newState({ isS1Audit: true, challenge: 9, am: 1e30 });
  state.bought[1] = 10;
  assert.equal(AD.dimCostExponent(state, 1), AD.dimCostExponent(state, 3));
  AD.buyDim(state, 1, 9);
  assert.equal(state.costBumps[3], 0);
  AD.buyDim(state, 1, 1);
  assert.equal(state.costBumps[3], 1);
  state.ipMult = 16;
  assert.equal(AD.s1.ipGain(state), 16);
  state.achs = { 55: true };
  assert.equal(AD.s1.startingAM(state), 5e10);
  assert.equal(AD.s1.startingBoosts(state), 0);
  assert.equal(S1SIM.canBuyIU({}, "IU22"), false);
  assert.equal(S1SIM.canBuyIU({ IU12: true }, "IU22"), true);
  assert.equal(AD.newState({ isS1Audit: true }).achs[76], undefined);
}
function verifyLedger(flow) {
  let previous = 0;
  let displayedSum = 0;
  let ip = 1;
  const upgrades = {};
  for (const row of flow.selected.rows) {
    assert.ok(Math.abs(row.cumulative - previous - row.wait) < 1e-5);
    displayedSum += Math.round(row.cumulative) - Math.round(previous);
    previous = row.cumulative;
    ip += row.runs;
    const key = row.item.split(" ")[0];
    if (S1SIM.IU_BY_KEY[key]) {
      assert.ok(S1SIM.canBuyIU(upgrades, key));
      ip -= S1SIM.IU_BY_KEY[key].cost;
      upgrades[key] = true;
    }
    assert.equal(ip, row.ip);
    assert.ok(ip >= 0 && Number.isInteger(ip));
  }
  assert.equal(displayedSum, Math.round(flow.selected.seconds));
}
function verifySelected(flow) {
  const config = flow.selected.c9Config;
  const before = JSON.stringify(config);
  const result = S1SIM.runInfinity(config);
  assert.ok(result.ok);
  assert.equal(JSON.stringify(config), before);
  assert.equal(result.ipGained, 1);
  assert.ok(Math.abs(result.time - flow.selected.c9Seconds) < 1e-6);
  assert.equal(config.brk, false);
  assert.equal(result.idBought[1], 0);
  assert.deepEqual(config.c9AutoTiers, []);
  assert.equal(config.achOverride[78], undefined);
  assert.equal(flow.candidates.length, 90);
  const completed = flow.candidates.filter(candidate => candidate.ok);
  assert.equal(Math.min(...completed.map(candidate => candidate.seconds)), flow.selected.seconds);
}
function verifyPreparation(flow) {
  const route = S1ROUTE.createRoute();
  for (const row of flow.selected.rows.filter(entry => entry.farmRuns)) {
    for (const record of row.farmRuns) {
      const result = S1SIM.runInfinity(S1ROUTE.configuration(route, {
        challenge: 0, boostCap: record.boostCap, galaxyCap: record.galaxyCap }));
      assert.ok(result.ok);
      assert.ok(Math.abs(result.time - record.seconds) < 1e-6);
      route.elapsed += result.time;
      route.ip += result.ipGained;
      route.infinities++;
      route.achievements = Object.fromEntries(result.achievements.map(id => [id, true]));
      for (const [id, seconds] of [[37,7200],[54,600],[55,60],[78,0.25]]) {
        if (result.time <= seconds) route.achievements[id] = true;
      }
      if (result.galaxies === 1) route.achievements[36] = true;
    }
    const key = row.item.split(" ")[0];
    if (S1SIM.IU_BY_KEY[key]) {
      route.upgrades[key] = true;
      route.ip -= S1SIM.IU_BY_KEY[key].cost;
    }
    assert.ok(Math.abs(route.elapsed - row.cumulative) < 1e-5);
    assert.equal(route.ip, row.ip);
  }
  assert.deepEqual(route.achievements, flow.selected.c9Config.achOverride);
}
verifyMechanics();
if (process.argv.includes("--generate")) {
  const flow = S1ROUTE.generate(progress => console.log(JSON.stringify(progress)));
  fs.writeFileSync(path.join(ROOT, "js/s1flow.js"),
    "/* Generated by tools/s1-audit.cjs --generate. */\nwindow.S1FLOW = " + JSON.stringify(flow, null, 2) + ";\n");
}
require(path.join(ROOT, "js/s1flow.js"));
verifyLedger(S1FLOW);
verifySelected(S1FLOW);
if (process.argv.includes("--replay")) verifyPreparation(S1FLOW);
console.log(JSON.stringify({ status: "PASS", version: S1FLOW.version, rows: S1FLOW.selected.rows.length,
  candidates: S1FLOW.candidates.length, seconds: S1FLOW.selected.seconds, c9Seconds: S1FLOW.selected.c9Seconds }));
